### ISSUE TITLE
Apparent deprecation

### ISSUE THREAD

**Issue by dcousens** [toddbluhm/cordova-plugin-launchscreen-storyboard#2]
In https://github.com/toddbluhm/cordova-plugin-launchscreen-storyboard/commit/d6c9c11bf461baeee9193bc52103ae70a844037c, you added:

``` markdown
**Note: This plugin has become somewhat useless
now that `cordova-ios` requires that you use their
built-in launch screen image solution.**

```

Can you elaborate on this?
I use `CDVLaunchScreen` with this plugin as a way to control the launch screen,  something that [for me] failed to work with existing plugins.

**Comment by toddbluhm** [comment]
It actually works with `CDVLaunchScreen`?! I did not realize it worked with that.

I wrote this plugin before the `CDVLaunchScreen` to enable storyboards in my app. Then they forced us into using `CDVLaunchScreen` and it broke my intended purpose for the plugin, hence the warning. If you want to update the docs to remove the warning and mention it working with `CDVLaunchScreen` and a little example code that would be awesome 😄

I appreciate you mentioning this to me.

**Comment by dcousens** [comment]
``` xml
<preference name="StoryboardName" value="CDVLaunchScreen" />
```

Personally,  I'd recommend you [we?] change that to the default so this plugin just works "out of the box" for most users :+1:

**Comment by toddbluhm** [comment]
Yeah I'm all for changing it to the default now that I know it works! As for the preferences stuff it should work like you said. I followed the Cordova plugin guide for it...but maybe I did something wrong? I will look into why preferences aren't changing the value.

**Comment by toddbluhm** [comment]
Ignore the last part. I just saw your PR

**Comment by dcousens** [comment]
@toddbluhm in light of https://github.com/toddbluhm/cordova-plugin-launchscreen-storyboard/pull/4#issuecomment-270551913,  I'll let you close this via the README cleanup :+1:

**Comment by toddbluhm** [comment]
Closed by commit: https://github.com/toddbluhm/cordova-plugin-launchscreen-storyboard/commit/45338424a39b6484e17872e67c770e0bdee5b286
