### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by dcousens** [toddbluhm/cordova-plugin-launchscreen-storyboard#3]
Out of interest,  how *do* you change the `StoryboardName` in your `config.xml`?
I've had no luck with the configuration copying to `ios/AppName/config.xml` or `ios/ios.json`.

Short of my current approach which is to just change the `StoryboardName` manually in these files,  what am I doing wrong?

I haven't had this problem with other plugins :cry: 

I am putting
``` xml
<preference name="StoryboardName" value="LaunchScreen" />
```

Directly in my `config.xml`,  with its parent element being the `widget`.
I've also tried putting it inside the `feature` element, copy-pasted from the `README`,  and I've also tried putting it inside `<platform name="ios">`,  with and without the `feature` element.

**edit:** it appears to be a bug, see #4 :stuck_out_tongue:

**Comment by toddbluhm** [comment]
Thanks for this!
